services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: yukpo_db
      POSTGRES_USER: yukpo_user
      POSTGRES_PASSWORD: yukpo_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    image: rust:1.75
    working_dir: /app
    command: >
      sh -c "
      apt-get update && 
      apt-get install -y pkg-config libssl-dev libpq-dev && 
      cd /app && 
      cargo build --release && 
      ./target/release/yukpo-backend
      "
    environment:
      DATABASE_URL: postgresql://yukpo_user:yukpo_password@postgres:5432/yukpo_db
      HOST: 0.0.0.0
      PORT: 3001
      ENVIRONMENT: production
      RUST_LOG: info
    ports:
      - '3001:3001'
    depends_on:
      - postgres
    volumes:
      - ./backend:/app

  frontend:
    image: node:18-alpine
    working_dir: /app
    command: >
      sh -c "
      npm install && 
      npm run dev -- --host 0.0.0.0 --port 3000
      "
    environment:
      VITE_API_BASE_URL: http://localhost:3001
      VITE_APP_GOOGLE_MAPS_API_KEY: AIzaSyDFfWEq1Umm06SNTbR-cRhRQ5Sq_taEAWQ
      VITE_APP_PINECONE_API_KEY: pcsk_6aD9si_CSCQPpYjfbVR5VKmqaZQYDu2P49KsvSBvbgUftR24tRMYp7YesZfNWDrALRhdmu
      VITE_WEBSOCKET_ENABLED: true
      VITE_WEBSOCKET_URL: ws://localhost:3001/ws
    ports:
      - '3000:3000'
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

volumes:
  postgres_data:
