version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: yukpo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Hernandez87
    ports:
      - "5432:5432"
