import { MD3DarkTheme, MD3LightTheme } from 'react-native-paper';

export const lightTheme = {
    ...MD3LightTheme,
    colors: {
        ...MD3LightTheme.colors,
        primary: '#2563eb',
        primaryContainer: '#dbeafe',
        secondary: '#64748b',
        secondaryContainer: '#f1f5f9',
        tertiary: '#7c3aed',
        tertiaryContainer: '#ede9fe',
        surface: '#ffffff',
        surfaceVariant: '#f8fafc',
        background: '#ffffff',
        error: '#dc2626',
        errorContainer: '#fef2f2',
        onPrimary: '#ffffff',
        onPrimaryContainer: '#1e40af',
        onSecondary: '#ffffff',
        onSecondaryContainer: '#334155',
        onTertiary: '#ffffff',
        onTertiaryContainer: '#5b21b6',
        onSurface: '#0f172a',
        onSurfaceVariant: '#475569',
        onBackground: '#0f172a',
        onError: '#ffffff',
        onErrorContainer: '#991b1b',
        outline: '#cbd5e1',
        outlineVariant: '#e2e8f0',
        shadow: '#000000',
        scrim: '#000000',
        inverseSurface: '#1e293b',
        inverseOnSurface: '#f1f5f9',
        inversePrimary: '#93c5fd',
        elevation: {
            level0: 'transparent',
            level1: '#f8fafc',
            level2: '#f1f5f9',
            level3: '#e2e8f0',
            level4: '#cbd5e1',
            level5: '#94a3b8',
        },
    },
};

export const darkTheme = {
    ...MD3DarkTheme,
    colors: {
        ...MD3DarkTheme.colors,
        primary: '#3b82f6',
        primaryContainer: '#1e40af',
        secondary: '#94a3b8',
        secondaryContainer: '#334155',
        tertiary: '#8b5cf6',
        tertiaryContainer: '#5b21b6',
        surface: '#0f172a',
        surfaceVariant: '#1e293b',
        background: '#0f172a',
        error: '#f87171',
        errorContainer: '#7f1d1d',
        onPrimary: '#ffffff',
        onPrimaryContainer: '#dbeafe',
        onSecondary: '#ffffff',
        onSecondaryContainer: '#cbd5e1',
        onTertiary: '#ffffff',
        onTertiaryContainer: '#ede9fe',
        onSurface: '#f1f5f9',
        onSurfaceVariant: '#cbd5e1',
        onBackground: '#f1f5f9',
        onError: '#ffffff',
        onErrorContainer: '#fef2f2',
        outline: '#475569',
        outlineVariant: '#334155',
        shadow: '#000000',
        scrim: '#000000',
        inverseSurface: '#f1f5f9',
        inverseOnSurface: '#1e293b',
        inversePrimary: '#1e40af',
        elevation: {
            level0: 'transparent',
            level1: '#1e293b',
            level2: '#334155',
            level3: '#475569',
            level4: '#64748b',
            level5: '#94a3b8',
        },
    },
};

export const theme = lightTheme;

