#!/usr/bin/env bash
# Script EAS Build hook qui s'exécute APRÈS npm install

set -e

echo "🔧 EAS Build post-install: Fixing Metro exports and worklets..."

# Fix react-native-worklets-core plugin.js FIRST (CRITICAL)
echo "🔧 Fixing react-native-worklets-core plugin.js..."
if [ -f "fix-worklets-core-plugin.js" ]; then
    node fix-worklets-core-plugin.js || {
        echo "❌ Worklets fix failed!"
        exit 1
    }
else
    echo "❌ fix-worklets-core-plugin.js not found!"
    exit 1
fi

# Forcer l'exécution des scripts de correction Metro
echo "📦 Running Metro exports fix..."
if [ -f "fix-metro-exports-comprehensive.js" ]; then
    node fix-metro-exports-comprehensive.js || {
        echo "❌ Metro fix failed!"
        exit 1
    }
else
    echo "❌ fix-metro-exports-comprehensive.js not found!"
    exit 1
fi

echo "🔗 Creating Metro private symlinks..."
if [ -f "create-metro-private-links.js" ]; then
    node create-metro-private-links.js || echo "⚠️ Symlinks creation failed (may not be critical)"
fi

# ✅ CORRIGÉ: Créer gradle.properties dans expo-modules-core/android pour définir kotlinVersion et Android SDK
echo "🔧 Creating gradle.properties in expo-modules-core/android for kotlinVersion and Android SDK..."
EXPO_MODULES_CORE_ANDROID="node_modules/expo-modules-core/android"
if [ -d "$EXPO_MODULES_CORE_ANDROID" ]; then
    cat > "$EXPO_MODULES_CORE_ANDROID/gradle.properties" << 'EOF'
# Auto-generated by eas-build-post-install.sh
# Defines kotlinVersion and Android SDK versions for expo-modules-core build
kotlinVersion=1.9.25
android.kotlinVersion=1.9.25
android.buildToolsVersion=35.0.0
android.minSdkVersion=24
android.compileSdkVersion=35
android.targetSdkVersion=35
EOF
    echo "✅ gradle.properties created in expo-modules-core/android"
else
    echo "⚠️ expo-modules-core/android directory not found"
fi

# ✅ CORRIGÉ: Ajouter le plugin Kotlin dans le buildscript de expo-modules-core/android/build.gradle
echo "🔧 Adding Kotlin plugin to expo-modules-core/android/build.gradle buildscript..."
if [ -f "fix-expo-modules-core-kotlin.js" ]; then
    # Vérifier que le fichier existe avant de le modifier
    EXPO_MODULES_BUILD_GRADLE="$EXPO_MODULES_CORE_ANDROID/build.gradle"
    if [ ! -f "$EXPO_MODULES_BUILD_GRADLE" ]; then
        echo "⚠️ expo-modules-core/android/build.gradle not found, skipping fix"
    else
        echo "   Found build.gradle at: $EXPO_MODULES_BUILD_GRADLE"
        echo "   File size before fix: $(wc -c < "$EXPO_MODULES_BUILD_GRADLE") bytes"
        echo "   First line: $(head -n 1 "$EXPO_MODULES_BUILD_GRADLE")"
        
        node fix-expo-modules-core-kotlin.js || {
            echo "❌ CRITICAL: Failed to add Kotlin plugin to expo-modules-core/android/build.gradle"
            echo "   This will cause the Gradle build to fail with 'unable to resolve class KotlinCompile'"
            echo "   Verifying file state..."
            if [ -f "$EXPO_MODULES_BUILD_GRADLE" ]; then
                echo "   First 10 lines of build.gradle:"
                head -n 10 "$EXPO_MODULES_BUILD_GRADLE"
            fi
            exit 1
        }
        
        # Vérifier que le fix a été appliqué
        if [ -f "$EXPO_MODULES_BUILD_GRADLE" ]; then
            echo "   File size after fix: $(wc -c < "$EXPO_MODULES_BUILD_GRADLE") bytes"
            echo "   First line: $(head -n 1 "$EXPO_MODULES_BUILD_GRADLE")"
            if grep -q "buildscript" "$EXPO_MODULES_BUILD_GRADLE" && grep -q "kotlin-gradle-plugin" "$EXPO_MODULES_BUILD_GRADLE"; then
                echo "✅ Kotlin plugin fix verified successfully"
            else
                echo "⚠️ WARNING: Fix may not have been applied correctly"
                echo "   Checking if buildscript exists: $(grep -c 'buildscript' "$EXPO_MODULES_BUILD_GRADLE" || echo '0')"
                echo "   Checking if kotlin plugin exists: $(grep -c 'kotlin-gradle-plugin' "$EXPO_MODULES_BUILD_GRADLE" || echo '0')"
            fi
        fi
    fi
else
    echo "❌ CRITICAL: fix-expo-modules-core-kotlin.js not found"
    echo "   This script is required to fix the KotlinCompile import issue"
    exit 1
fi

echo "✅ EAS Build post-install completed successfully"
exit 0

