[edge]
livekit-vps ansible_host=46.224.14.85 ansible_user=root   livekit_domain=livekit.46.224.14.85.sslip.io   srs_domain=srs.46.224.14.85.sslip.io   livekit_api_key=APIPHE9xDv5RPaP   livekit_api_secret=qVRL18gIk8W3Dp8V4Wu23I99t0XbZ5pM66D9i5MTTkE   acme_email=lelehernandez2007@yahoo.fr
