listen              1935;
max_connections     2000;
srs_log_tank        console;

daemon              off;

http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
    crossdomain     on;
}

http_api {
    enabled         on;
    listen          1985;
}

hls {
    enabled         on;
    hls_cleanup     on;
    hls_fragment    6;
    hls_window      60;
    hls_path        ./objs/nginx/html/live;
    hls_wait_keyframe on;
}

vhost __defaultVhost__ {
    hls {
        enabled             on;
        hls_fragment        6;
        hls_window          60;
        hls_path            ./objs/nginx/html/live;
    }

    http_remux {
        enabled     on;
        mount       [app]/[stream].m3u8;
    }
}


